name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 3
          --health-timeout 5s
        ports:
          - 5432:5432
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go
    
    - name: Checkout code
      uses: actions/checkout@v3
      id: checkout

    - name: Install golang migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate

    - name: Run migration
      run: make migrateup

    - name: Test
      run: make test
      id: test
    
    - name: Slack Notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.NOTI_BOT_WEBHOOK_URL }}
        SLACK_BOT_NAME: "noti-bot"
      run: |
        curl -X POST --data-urlencode "payload={\"channel\": \"#notibot\", \"username\": \"noti-bot\", \"text\": \"CI test successfully\", \"icon_emoji\": \":ghost:\"}" $SLACK_WEBHOOK_URL