name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go
    
    - name: Checkout code
      uses: actions/checkout@v3
      id: checkout

    - name: Test
      run: make test